### ISSUE TITLE
Package Compatibility and Robot Connection Issues

### ISSUE THREAD

**Issue by Nima-Fazeli** [mcubelab/abb-ros-catkin#1]
Is this package compatible with ros-indigo? 

There seems to be some sort of connection issue, steps to recreate the issue:
1- Currently Robot 1 is on the IP: 192.168.37.3
2- Ubuntu operating system is 14.04 Trusty running ros-indigo
3- Robot is pinged at the IP and responds.
4- The robot IP is correctly added to the ROS PARAM server.
5- Upon execution terminal output is:
``````````````````````````````````````
started core service [/rosout]
process[robot_node1-2]: started with pid [16299]
[ INFO] [1496673485.991432738]: ROBOT_CONTROLLER: Connecting to the ABB motion server...
[ INFO] [1496673485.996447858]: ROBOT_CONTROLLER: Connecting to the ABB logger server...
[ INFO] [1496673485.997628651]: ROBOT_CONTROLLER: Setting robot default configuration...
````````````````````````````````````````````
The robot_node.cpp stops in the execution of ``bool RobotController::setWorkObject()``, exactly on the line of ``if(sendAndReceive(message ...))``, it appears that ``sendAndReceive()'' is not getting a response. Is there some issue with compatibility from the `catkinization'?

**Comment by peterkty** [comment]
I think the robot for ARC has been changed to 192.168.37.100. You can find the ip on the teach pendant.

Why do you run it on Ubuntu 14.04? ARC computers should be all upgraded. In theory it does not depend on which version of Ubuntu and ROS.

Peter

**Comment by Nima-Fazeli** [comment]
This is not for the ARC, as mentioned it is for robot1 (the 120 on the right side). The Brix connected to it is running 14.04.

The ARC robot is indeed on 192.168.37.100, today (Tuesday) we checked with Carlos.

**Comment by peterkty** [comment]
Then the ip is something else for 120. Which is also on the teach pendant of that robot.

Peter

**Comment by Nima-Fazeli** [comment]
Problem has been resolved, it was an issue with a mismatch between the RAPID code and the updated robot_node.

Two new ROSPARAM variables need to be defined:
`````````````````````````
accelerationStart: 28
accelerationEnd: 28
``````````````````````````
With these new parameters the node should work.
